= NTP RTC Library for ESP8266 =

This library will use a combination of NTP and a virtual internal RTC to keep
time. It will sync up with NTP every 12 hours and use the internal timer to 
keep accurate time in between updates.

For more information about this library please visit us at


== License ==

Copyright (c) Richard Wardlow. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
